options(prompt="R>")
library(dplyr)
library(ggplot2)
library(tidyr)
getwd()
setwd("C:/R Programming")
data<-read.csv("C:/R Programming/Mental Health Dataset.csv")
summary(data)
missing_values<-sapply(data,function(x)sum(is.na(x)))
print(missing_values)
str(data)
